export const categories = [
  { slug: "seeds", name: "Seeds", emoji: "🌱", blurb: "Hybrid & organic seeds" },
  {
    slug: "crop-protection",
    name: "Crop Protection",
    emoji: "🛡️",
    blurb: "Herbicides & pesticides",
  },
  { slug: "nutrition", name: "Plant Nutrition", emoji: "🧪", blurb: "Fertilizers & bio-inputs" },
  { slug: "fungicides", name: "Fungicides", emoji: "🍄", blurb: "Fungal disease control" },
  { slug: "insecticides", name: "Insecticides", emoji: "🐛", blurb: "Pest & insect control" },
  { slug: "tools", name: "Farm Tools", emoji: "🛠️", blurb: "Sprayers, gear & more" },
];

export const products = [
  {
    id: "p1",
    name: "Kaveri Cotton Hybrid Seeds",
    category: "seeds",
    price: 850,
    mrp: 950,
    unit: "475 g pack",
    rating: 4.6,
    seller: "Kaveri Seeds",
    desc: "High-yield BT cotton hybrid, drought tolerant, suitable for kharif season.",
  },
  {
    id: "p2",
    name: "Urea 46% Nitrogen",
    category: "nutrition",
    price: 320,
    mrp: 350,
    unit: "45 kg bag",
    rating: 4.5,
    seller: "IFFCO",
    desc: "Prilled urea for boosting vegetative growth across all crops.",
  },
  {
    id: "p3",
    name: "Glyphosate 41% Herbicide",
    category: "crop-protection",
    price: 540,
    mrp: 620,
    unit: "1 L bottle",
    rating: 4.4,
    seller: "Bayer",
    desc: "Broad-spectrum weed control for pre-sowing operations.",
  },
  {
    id: "p4",
    name: "Mancozeb 75% WP",
    category: "fungicides",
    price: 410,
    mrp: 470,
    unit: "1 kg pouch",
    rating: 4.7,
    seller: "UPL",
    desc: "Contact fungicide effective against blight and downy mildew.",
  },
  {
    id: "p5",
    name: "Imidacloprid 17.8% SL",
    category: "insecticides",
    price: 380,
    mrp: 420,
    unit: "500 ml bottle",
    rating: 4.5,
    seller: "Syngenta",
    desc: "Systemic insecticide for aphids, jassids, and whiteflies.",
  },
  {
    id: "p6",
    name: "Battery Knapsack Sprayer 16L",
    category: "tools",
    price: 2650,
    mrp: 3100,
    unit: "1 unit",
    rating: 4.6,
    seller: "Aspee",
    desc: "Rechargeable battery-operated sprayer with adjustable nozzle.",
  },
  {
    id: "p7",
    name: "Paddy MTU 1010 Seeds",
    category: "seeds",
    price: 620,
    mrp: 680,
    unit: "10 kg bag",
    rating: 4.5,
    seller: "Nuziveedu",
    desc: "Medium-duration paddy variety with high grain quality.",
  },
  {
    id: "p8",
    name: "DAP Fertilizer 18-46-0",
    category: "nutrition",
    price: 1450,
    mrp: 1550,
    unit: "50 kg bag",
    rating: 4.7,
    seller: "IFFCO",
    desc: "Complex phosphorus fertilizer for root development.",
  },
];

export const services = [
  {
    slug: "drone",
    name: "Drone Spraying",
    short: "Precision spraying that saves water, time and chemicals.",
  },
  {
    slug: "harvester",
    name: "Harvester Rental",
    short: "Book combine harvesters at fair, transparent rates.",
  },
  {
    slug: "tractor",
    name: "Tractor Booking",
    short: "Plough, till and transport with certified tractor operators.",
  },
  {
    slug: "workforce",
    name: "Skilled Workforce",
    short: "Trained labour for sowing, harvesting and construction.",
  },
];
