export const categories = [
  { slug: "seeds", name: "Seeds", image: "/seeds.png", blurb: "Hybrid & organic seeds" },
  {
    slug: "crop-protection",
    name: "Crop Protection",
    image: "/crop-protection.png",
    blurb: "Herbicides & pesticides",
  },
  { slug: "nutrition", name: "Plant Nutrition", image: "/nutrition.png", blurb: "Fertilizers & bio-inputs" },
  { slug: "fungicides", name: "Fungicides", image: "/fungicides.png", blurb: "Fungal disease control" },
  { slug: "insecticides", name: "Insecticides", image: "/insecticides.png", blurb: "Pest & insect control" },
  { slug: "tools", name: "Farm Tools", image: "/tools.png", blurb: "Sprayers, gear & more" },
];

export const products = [
  {
    id: "p1",
    name: "Kaveri Cotton Hybrid Seeds",
    category: "seeds",
    price: 850,
    mrp: 950,
    unit: "475 g pack",
    rating: 4.6,
    seller: "Kaveri Seeds",
    desc: "High-yield BT cotton hybrid, drought tolerant, suitable for kharif season.",
  },
  {
    id: "p2",
    name: "Urea 46% Nitrogen",
    category: "nutrition",
    price: 320,
    mrp: 350,
    unit: "45 kg bag",
    rating: 4.5,
    seller: "IFFCO",
    desc: "Prilled urea for boosting vegetative growth across all crops.",
  },
  {
    id: "p3",
    name: "Glyphosate 41% Herbicide",
    category: "crop-protection",
    price: 540,
    mrp: 620,
    unit: "1 L bottle",
    rating: 4.4,
    seller: "Bayer",
    desc: "Broad-spectrum weed control for pre-sowing operations.",
  },
  {
    id: "p4",
    name: "Mancozeb 75% WP",
    category: "fungicides",
    price: 410,
    mrp: 470,
    unit: "1 kg pouch",
    rating: 4.7,
    seller: "UPL",
    desc: "Contact fungicide effective against blight and downy mildew.",
  },
  {
    id: "p5",
    name: "Imidacloprid 17.8% SL",
    category: "insecticides",
    price: 380,
    mrp: 420,
    unit: "500 ml bottle",
    rating: 4.5,
    seller: "Syngenta",
    desc: "Systemic insecticide for aphids, jassids, and whiteflies.",
  },
  {
    id: "p6",
    name: "Battery Knapsack Sprayer 16L",
    category: "tools",
    price: 2650,
    mrp: 3100,
    unit: "1 unit",
    rating: 4.6,
    seller: "Aspee",
    desc: "Rechargeable battery-operated sprayer with adjustable nozzle.",
  },
  {
    id: "p7",
    name: "Paddy MTU 1010 Seeds",
    category: "seeds",
    price: 620,
    mrp: 680,
    unit: "10 kg bag",
    rating: 4.5,
    seller: "Nuziveedu",
    desc: "Medium-duration paddy variety with high grain quality.",
  },
  {
    id: "p8",
    name: "DAP Fertilizer 18-46-0",
    category: "nutrition",
    price: 1450,
    mrp: 1550,
    unit: "50 kg bag",
    rating: 4.7,
    seller: "IFFCO",
    desc: "Complex phosphorus fertilizer for root development.",
  },
  {
    id: "p9",
    name: "Kanak Paddy Seeds",
    category: "seeds",
    price: 750,
    mrp: 800,
    unit: "10 kg bag",
    rating: 4.4,
    seller: "Kanak Seeds",
    desc: "High quality paddy seeds, disease resistant, high yield.",
  },
  {
    id: "p10",
    name: "Nuziveedu Maize Seeds",
    category: "seeds",
    price: 1200,
    mrp: 1350,
    unit: "4 kg pack",
    rating: 4.6,
    seller: "Nuziveedu",
    desc: "Hybrid maize seeds with high grain weight and drought tolerance.",
  },
  {
    id: "p11",
    name: "Organic Neem Oil 1500 PPM",
    category: "crop-protection",
    price: 280,
    mrp: 320,
    unit: "250 ml bottle",
    rating: 4.3,
    seller: "Multiplex",
    desc: "Eco-friendly botanical extract for organic pest control.",
  },
  {
    id: "p12",
    name: "Bayer Confidor Insecticide",
    category: "crop-protection",
    price: 490,
    mrp: 550,
    unit: "100 ml bottle",
    rating: 4.7,
    seller: "Bayer",
    desc: "Highly effective systemic insecticide for sucking pests.",
  },
  {
    id: "p13",
    name: "Sudarshan Urea Bag",
    category: "nutrition",
    price: 330,
    mrp: 360,
    unit: "45 kg bag",
    rating: 4.5,
    seller: "Sudarshan Chemicals",
    desc: "Premium grade nitrogen fertilizer for robust crop growth.",
  },
  {
    id: "p14",
    name: "Muriate of Potash (MOP)",
    category: "nutrition",
    price: 980,
    mrp: 1100,
    unit: "50 kg bag",
    rating: 4.6,
    seller: "IPL",
    desc: "Potassic fertilizer essential for grain quality and disease resistance.",
  },
  {
    id: "p15",
    name: "Tata Rallis Contaf Plus Fungicide",
    category: "fungicides",
    price: 610,
    mrp: 690,
    unit: "1 L bottle",
    rating: 4.5,
    seller: "Tata Rallis",
    desc: "Systemic triazole fungicide with protective and curative action.",
  },
  {
    id: "p16",
    name: "Copper Oxychloride 50% WP",
    category: "fungicides",
    price: 350,
    mrp: 400,
    unit: "500 g pack",
    rating: 4.4,
    seller: "UPL",
    desc: "Broad spectrum contact fungicide for blight and leaf spot control.",
  },
  {
    id: "p17",
    name: "Syngenta Cruiser Insecticide",
    category: "insecticides",
    price: 780,
    mrp: 850,
    unit: "100 g pack",
    rating: 4.8,
    seller: "Syngenta",
    desc: "Broad-spectrum seed treatment insecticide for early crop protection.",
  },
  {
    id: "p18",
    name: "Coromandel Organic Manure",
    category: "nutrition",
    price: 450,
    mrp: 500,
    unit: "40 kg bag",
    rating: 4.5,
    seller: "Coromandel",
    desc: "Well-decomposed organic manure enriched with beneficial microbes.",
  },
  {
    id: "p19",
    name: "Fiskars Pruning Hand Saw",
    category: "tools",
    price: 1850,
    mrp: 2100,
    unit: "1 unit",
    rating: 4.7,
    seller: "Fiskars",
    desc: "Ergonomic pull stroke pruning saw with ultra sharp steel blade.",
  },
  {
    id: "p20",
    name: "Falcon Hedge Shear Classic",
    category: "tools",
    price: 950,
    mrp: 1100,
    unit: "1 unit",
    rating: 4.5,
    seller: "Falcon",
    desc: "Professional grass and hedge trimming shears with wooden handles.",
  },
  {
    id: "p21",
    name: "Tomato Hybrid Seeds (Utsav)",
    category: "seeds",
    price: 320,
    mrp: 350,
    unit: "10 g packet",
    rating: 4.5,
    seller: "Seminis",
    desc: "High yield hybrid tomato seeds, disease resistant, firm fruits.",
  },
  {
    id: "p22",
    name: "Chilli G4 Hybrid Seeds",
    category: "seeds",
    price: 450,
    mrp: 500,
    unit: "10 g packet",
    rating: 4.6,
    seller: "VNR Seeds",
    desc: "High spiciness dark green hybrid chilli seeds, high productivity.",
  },
  {
    id: "p23",
    name: "NPK 19-19-19 Soluble Fertilizer",
    category: "nutrition",
    price: 180,
    mrp: 220,
    unit: "1 kg pouch",
    rating: 4.6,
    seller: "Mahadhan",
    desc: "100% water soluble complex fertilizer for foliar application.",
  },
  {
    id: "p24",
    name: "Zinc Sulphate Monohydrate 33%",
    category: "nutrition",
    price: 240,
    mrp: 280,
    unit: "5 kg bag",
    rating: 4.4,
    seller: "Multiplex",
    desc: "Micro-nutrient fertilizer to prevent zinc deficiency in crops.",
  },
  {
    id: "p25",
    name: "Bayer Nativo Fungicide",
    category: "fungicides",
    price: 890,
    mrp: 990,
    unit: "100 g pack",
    rating: 4.8,
    seller: "Bayer",
    desc: "Premium systemic fungicide for blast and leaf spot disease.",
  },
  {
    id: "p26",
    name: "Syngenta Amistar Fungicide",
    category: "fungicides",
    price: 1350,
    mrp: 1500,
    unit: "200 ml bottle",
    rating: 4.7,
    seller: "Syngenta",
    desc: "Broad-spectrum strobilurin fungicide with systemic action.",
  },
  {
    id: "p27",
    name: "Cartap Hydrochloride 4G",
    category: "insecticides",
    price: 520,
    mrp: 580,
    unit: "5 kg bag",
    rating: 4.5,
    seller: "Dhanuka",
    desc: "Granular insecticide for stem borer control in paddy crops.",
  },
  {
    id: "p28",
    name: "Fipronil 5% SC Insecticide",
    category: "insecticides",
    price: 640,
    mrp: 720,
    unit: "1 L bottle",
    rating: 4.6,
    seller: "Gharda Chemicals",
    desc: "Highly effective contact and systemic insecticide for thrips.",
  },
  {
    id: "p29",
    name: "Hand Weed Hoe Tool (Heavy Duty)",
    category: "tools",
    price: 380,
    mrp: 450,
    unit: "1 unit",
    rating: 4.3,
    seller: "KisanKraft",
    desc: "Durable carbon steel hand hoe tool for weeding and soil aeration.",
  },
  {
    id: "p30",
    name: "Agri Sickle Steel (Premium)",
    category: "tools",
    price: 150,
    mrp: 180,
    unit: "1 unit",
    rating: 4.5,
    seller: "Tata Agrico",
    desc: "High quality curved steel sickle for manual harvesting.",
  },
];

export const services = [
  {
    slug: "drone",
    name: "Drone Spraying",
    short: "Precision spraying that saves water, time and chemicals.",
  },
  {
    slug: "harvester",
    name: "Harvester Rental",
    short: "Book combine harvesters at fair, transparent rates.",
  },
  {
    slug: "tractor",
    name: "Tractor Booking",
    short: "Plough, till and transport with certified tractor operators.",
  },
  {
    slug: "workforce",
    name: "Skilled Workforce",
    short: "Trained labour for sowing, harvesting and construction.",
  },
];
