/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as OrdersBookingIdRouteImport } from './routes/orders.booking.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersBookingIdRoute = OrdersBookingIdRouteImport.update({
  id: '/orders/booking/$id',
  path: '/orders/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/success': typeof BookingSuccessRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$service': typeof ServicesServiceRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/orders/booking/$id': typeof OrdersBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/success': typeof BookingSuccessRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$service': typeof ServicesServiceRoute
  '/orders': typeof OrdersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/orders/booking/$id': typeof OrdersBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/success': typeof BookingSuccessRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$service': typeof ServicesServiceRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/orders/booking/$id': typeof OrdersBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/booking/success'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/services/$service'
    | '/orders/'
    | '/services/'
    | '/orders/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/booking/success'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/services/$service'
    | '/orders'
    | '/services'
    | '/orders/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/booking/success'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/services/$service'
    | '/orders/'
    | '/services/'
    | '/orders/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  OrdersBookingIdRoute: typeof OrdersBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/booking/$id': {
      id: '/orders/booking/$id'
      path: '/orders/booking/$id'
      fullPath: '/orders/booking/$id'
      preLoaderRoute: typeof OrdersBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  OrdersBookingIdRoute: OrdersBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
