/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as CartRouteImport } from "./routes/cart";
import { Route as CheckoutRouteImport } from "./routes/checkout";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as ShopRouteImport } from "./routes/shop";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as BookingSuccessRouteImport } from "./routes/booking.success";
import { Route as CategorySlugRouteImport } from "./routes/category.$slug";
import { Route as OrdersIndexRouteImport } from "./routes/orders.index";
import { Route as OrdersIdRouteImport } from "./routes/orders.$id";
import { Route as ProductIdRouteImport } from "./routes/product.$id";
import { Route as ServicesIndexRouteImport } from "./routes/services.index";
import { Route as ServicesServiceRouteImport } from "./routes/services.$service";
import { Route as OrdersBookingIdRouteImport } from "./routes/orders.booking.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
});
const CartRoute = CartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
});
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
});
const ShopRoute = ShopRouteImport.update({
  id: "/shop",
  path: "/shop",
  getParentRoute: () => rootRouteImport,
});
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
});
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: "/booking/success",
  path: "/booking/success",
  getParentRoute: () => rootRouteImport,
});
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: "/category/$slug",
  path: "/category/$slug",
  getParentRoute: () => rootRouteImport,
});
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
});
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: "/orders/$id",
  path: "/orders/$id",
  getParentRoute: () => rootRouteImport,
});
const ProductIdRoute = ProductIdRouteImport.update({
  id: "/product/$id",
  path: "/product/$id",
  getParentRoute: () => rootRouteImport,
});
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: "/services/",
  path: "/services/",
  getParentRoute: () => rootRouteImport,
});
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: "/services/$service",
  path: "/services/$service",
  getParentRoute: () => rootRouteImport,
});
const OrdersBookingIdRoute = OrdersBookingIdRouteImport.update({
  id: "/orders/booking/$id",
  path: "/orders/booking/$id",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  OrdersBookingIdRoute: OrdersBookingIdRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
